name: Java CI without Maven

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Carregando o JAVA 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Etapa para compilar o código sem Maven
    - name: Compilar arquivos Java
      run: |
        mkdir -p out
        javac -d out $(find . -name "*.java")

    # Caso tenha um arquivo JAR para ser gerado
    - name: Gerar arquivo JAR
      run: |
        cd out
        jar cf ../app.jar *

    # Etapa de deploy no Render (mantém igual)
    - name: Render Deploy Action
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{secrets.ID}}
        api-key: ${{secrets.KEY}}
